### ISSUE TITLE
don't set fixmee keybindings like [C-c f], [C-c v] etc.

### ISSUE THREAD

**Issue by stardiviner** [rolandwalker/fixmee#11]
Those keybindings are usually reserved for user.
The better keybinding is `[C-c m]` prefix. then sub-keybindings.
I think `[M-g]` is better for this case. But don't conflict with Emacs built-in keybindings.

**Comment by punchagan** [comment]
The [key-binding conventions documentation](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html) could be helpful.

**Comment by stardiviner** [comment]
yes, but you can use `[M-g]` as prefix. And set keybinding not overriding the defualt `[M-g]` keybinidngs.
Because usually will bind `[C-c f]` etc to prefix. For example I bind `[C-c p]` for programming projectile prefix.

**Comment by rolandwalker** [comment]
Hi!  Thanks!

This has come up before — I'm aware of the key-binding conventions documentation, but also aware that many libraries do not follow that document.  Example: org-mode.

The situation is far from ideal.  My feeling is
 * we do best for the novice user by providing simple bindings
 * advanced users know exactly how to rebind as best makes sense to them
 * the bindings don't kick in unless you turn on the mode

and that is why I have made the choice of binding under `C-c`: so things will work easily for a novice.

I'd gladly accept a documentation patch noting this compromise, and describing how to reassign the bindings.

**Comment by stardiviner** [comment]
I see, thanks. I will disable the minor mode, and setup keybindings manually.

**Comment by stardiviner** [comment]
I realized this really need an customize variable `defcustom` to let user can custom fixmee keybindings.

**Comment by stardiviner** [comment]
I have an alternative option, provide an option `decustom fixmee-setup-keybindings`, so that user can decide whether auto setup keybindings when load `global-fixmee-mode` or `fixmee-mode`.
This option can be `t` by default. But some user like me can set it to `nil` to disable it when mode loaded.
What do you think?
I can't find alternative better similar extension like `fixmee`. But this keybinding issue is really annoying.
